version: "3.9"

services:
  ruby:
    build: 
      context: ruby
      dockerfile: Dockerfile
      platforms: 
        - linux/amd64
  node:
    build:
      context: node
      dockerfile: Dockerfile
      platforms:
        - linux/amd64
